// this file is automatically generated by git.version.ts script
export const versions = {
  version: '15.1.0',
  revision: '5e3a891e408d5545ff5b87ce568a486e06d6694f',
  branch: '5e3a891e408d5545ff5b87ce568a486e06d6694f',
};
