import { GlobalConfig } from './config.model';
import * as moment from 'moment';

export const DEFAULT_CFG: GlobalConfig = {
  misc: {
    isMinimizeToTrayOnExit: false,
    isConfirmBeforeExit: false,
    isNotifyWhenTimeEstimateExceeded: false,
    isBlockFinishDayUntilTimeTimeTracked: false,
    isOnlyOpenIdleWhenCurrentTask: false,
    isEnableIdleTimeTracking: true,
    minIdleTime: 5 * 60 * 1000,
    isTakeABreakEnabled: false,
    /* tslint:disable-next-line */
    takeABreakMessage: 'Take a break! You have been working for ${duration} without one. Go away from the computer! Take a short walk! Makes you more productive in the long run!',
    takeABreakMinWorkingTime: 60 * 60 * 1000,
  },
  pomodoro: {
    isEnabled: true,
    duration: moment.duration(45, 'minutes'),
    breakDuration: moment.duration(5, 'minutes'),
    longerBreakDuration: moment.duration(15, 'minutes'),
    cyclesBeforeLongerBreak: 4,
    isStopTrackingOnBreak: true,
    isStopTrackingOnLongBreak: true,
    isShowDistractionsOnBreak: true,
    isManualContinue: false,
    isPlaySound: true,
    isGoToWorkView: false,
    isPlayTick: false,
  },
  keyboard: {
    globalShowHide: 'Ctrl+Shift+X',
    addNewTask: '*',
    openProjectNotes: 'N',
    openDistractionPanel: 'D',
    showHelp: '?',
    goToDailyPlanner: 'p',
    goToWorkView: 'w',
    goToDailyAgenda: '',
    goToFocusMode: 'F',
    goToSettings: '',
    taskEditTitle: 'e',
    taskToggleNotes: 'n',
    taskOpenEstimationDialog: 't',
    taskToggleDone: 'd',
    taskAddSubTask: '+',
    taskDelete: 'Delete',
    selectPreviousTask: 'k',
    selectNextTask: 'j',
    moveTaskUp: 'Ctrl+Shift+ArrowUp',
    moveTaskDown: 'Ctrl+Shift+ArrowDown',
    moveToBacklog: 'B',
    moveToTodaysTasks: 'T',
    expandSubTasks: '',
    collapseSubTasks: '',
    togglePlay: 'y',
  },
  googleDriveSync: {
    isEnabled: false,
    isAutoLogin: false,
    isAutoSyncToRemote: false,
    isNotifyOnSync: false,
    isLoadRemoteDataOnStartup: false,
    syncInterval: 60 * 1000,
    syncFileName: 'SUPER_PRODUCTIVITY_SYNC.json',
    _lastLocalUpdate: null,
    _lastSyncToRemote: null,
    _backupDocId: null,
  },
  _uiHelper: {
    isShowWelcomeDialog: true,
    isShowBookmarkBar: false,
    showSubTasks: true
  },
  _googleSession: {
    accessToken: null,
    refreshToken: null,
    expiresAt: null
  },
};
