export const SYNC_INITIAL_SYNC_TRIGGER = 'INITIAL_SYNC_TRIGGER';
export const SYNC_DEFAULT_AUDIT_TIME = 10000;
export const SYNC_TRIGGER_FOCUS_AGAIN_TIMEOUT_DURATION = SYNC_DEFAULT_AUDIT_TIME + 3000;
export const SYNC_LONG_INACTIVITY = 1000 * 60 * 5;
export const SYNC_LONG_INACTIVITY_THROTTLE_TIME = 1000 * 45;
