export const T = {
  'BL': {
    'FROM_OTHER_PROJECTS': 'BL.FROM_OTHER_PROJECTS',
    'NO_SCHEDULED': 'BL.NO_SCHEDULED',
    'NO_TASKS': 'BL.NO_TASKS',
    'SCHEDULED': 'BL.SCHEDULED',
    'TITLE': 'BL.TITLE'
  },
  'F': {
    'ATTACHMENT': {
      'DIALOG_EDIT': {
        'ADD_ATTACHMENT': 'F.ATTACHMENT.DIALOG_EDIT.ADD_ATTACHMENT',
        'EDIT_ATTACHMENT': 'F.ATTACHMENT.DIALOG_EDIT.EDIT_ATTACHMENT',
        'LABELS': {
          'FILE': 'F.ATTACHMENT.DIALOG_EDIT.LABELS.FILE',
          'IMG': 'F.ATTACHMENT.DIALOG_EDIT.LABELS.IMG',
          'LINK': 'F.ATTACHMENT.DIALOG_EDIT.LABELS.LINK'
        },
        'SELECT_TYPE': 'F.ATTACHMENT.DIALOG_EDIT.SELECT_TYPE',
        'TYPES': {
          'FILE': 'F.ATTACHMENT.DIALOG_EDIT.TYPES.FILE',
          'IMG': 'F.ATTACHMENT.DIALOG_EDIT.TYPES.IMG',
          'LINK': 'F.ATTACHMENT.DIALOG_EDIT.TYPES.LINK'
        }
      },
      'LIST': {
        'NO_ATTACHMENTS': 'F.ATTACHMENT.LIST.NO_ATTACHMENTS'
      }
    },
    'BOOKMARK': {
      'BAR': {
        'DROP': 'F.BOOKMARK.BAR.DROP',
        'NO_BOOKMARKS': 'F.BOOKMARK.BAR.NO_BOOKMARKS'
      },
      'DIALOG_EDIT': {
        'ADD_BOOKMARK': 'F.BOOKMARK.DIALOG_EDIT.ADD_BOOKMARK',
        'EDIT_BOOKMARK': 'F.BOOKMARK.DIALOG_EDIT.EDIT_BOOKMARK',
        'LABELS': {
          'COMMAND': 'F.BOOKMARK.DIALOG_EDIT.LABELS.COMMAND',
          'FILE': 'F.BOOKMARK.DIALOG_EDIT.LABELS.FILE',
          'IMG': 'F.BOOKMARK.DIALOG_EDIT.LABELS.IMG',
          'LINK': 'F.BOOKMARK.DIALOG_EDIT.LABELS.LINK'
        },
        'SELECT_ICON': 'F.BOOKMARK.DIALOG_EDIT.SELECT_ICON',
        'SELECT_TYPE': 'F.BOOKMARK.DIALOG_EDIT.SELECT_TYPE',
        'TYPES': {
          'COMMAND': 'F.BOOKMARK.DIALOG_EDIT.TYPES.COMMAND',
          'FILE': 'F.BOOKMARK.DIALOG_EDIT.TYPES.FILE',
          'IMG': 'F.BOOKMARK.DIALOG_EDIT.TYPES.IMG',
          'LINK': 'F.BOOKMARK.DIALOG_EDIT.TYPES.LINK'
        }
      }
    },
    'CONFIG': {
      'SNACK': {
        'UPDATE_SECTION': 'F.CONFIG.SNACK.UPDATE_SECTION'
      }
    },
    'GOOGLE': {
      'DIALOG': {
        'CREATE_SYNC_FILE': 'F.GOOGLE.DIALOG.CREATE_SYNC_FILE',
        'USE_EXISTING_SYNC_FILE': 'F.GOOGLE.DIALOG.USE_EXISTING_SYNC_FILE'
      },
      'D_CONFIRM_LOAD': {
        'LAST_MOD': 'F.GOOGLE.D_CONFIRM_LOAD.LAST_MOD',
        'LAST_SYNC': 'F.GOOGLE.D_CONFIRM_LOAD.LAST_SYNC',
        'LOCAL': 'F.GOOGLE.D_CONFIRM_LOAD.LOCAL',
        'LOCAL_REMOTE': 'F.GOOGLE.D_CONFIRM_LOAD.LOCAL_REMOTE',
        'OVERWRITE_LOCAL': 'F.GOOGLE.D_CONFIRM_LOAD.OVERWRITE_LOCAL',
        'OVERWRITE_REMOTE': 'F.GOOGLE.D_CONFIRM_LOAD.OVERWRITE_REMOTE',
        'REMOTE': 'F.GOOGLE.D_CONFIRM_LOAD.REMOTE',
        'TEXT': 'F.GOOGLE.D_CONFIRM_LOAD.TEXT',
        'TITLE': 'F.GOOGLE.D_CONFIRM_LOAD.TITLE'
      },
      'D_CONFIRM_SAVE': {
        'LAST_MOD': 'F.GOOGLE.D_CONFIRM_SAVE.LAST_MOD',
        'LAST_SYNC': 'F.GOOGLE.D_CONFIRM_SAVE.LAST_SYNC',
        'LOCAL': 'F.GOOGLE.D_CONFIRM_SAVE.LOCAL',
        'LOCAL_REMOTE': 'F.GOOGLE.D_CONFIRM_SAVE.LOCAL_REMOTE',
        'OVERWRITE_LOCAL': 'F.GOOGLE.D_CONFIRM_SAVE.OVERWRITE_LOCAL',
        'OVERWRITE_REMOTE': 'F.GOOGLE.D_CONFIRM_SAVE.OVERWRITE_REMOTE',
        'REMOTE': 'F.GOOGLE.D_CONFIRM_SAVE.REMOTE',
        'TEXT': 'F.GOOGLE.D_CONFIRM_SAVE.TEXT',
        'TITLE': 'F.GOOGLE.D_CONFIRM_SAVE.TITLE'
      },
      'EXPORT_TIME': {
        'ALWAYS_ROUND_UP': 'F.GOOGLE.EXPORT_TIME.ALWAYS_ROUND_UP',
        'AUTO_LOGIN': 'F.GOOGLE.EXPORT_TIME.AUTO_LOGIN',
        'HELP_ADDITIONAL': 'F.GOOGLE.EXPORT_TIME.HELP_ADDITIONAL',
        'HELP_INFO': 'F.GOOGLE.EXPORT_TIME.HELP_INFO',
        'HELP_POSSIBLE_PROPERTIES': 'F.GOOGLE.EXPORT_TIME.HELP_POSSIBLE_PROPERTIES',
        'LOGIN': 'F.GOOGLE.EXPORT_TIME.LOGIN',
        'LOGOUT': 'F.GOOGLE.EXPORT_TIME.LOGOUT',
        'OPEN_SPREADSHEET': 'F.GOOGLE.EXPORT_TIME.OPEN_SPREADSHEET',
        'READ_SPREADSHEET': 'F.GOOGLE.EXPORT_TIME.READ_SPREADSHEET',
        'ROUND_END_TIME_TO': 'F.GOOGLE.EXPORT_TIME.ROUND_END_TIME_TO',
        'ROUND_HALF': 'F.GOOGLE.EXPORT_TIME.ROUND_HALF',
        'ROUND_HOUR': 'F.GOOGLE.EXPORT_TIME.ROUND_HOUR',
        'ROUND_QUARTER': 'F.GOOGLE.EXPORT_TIME.ROUND_QUARTER',
        'ROUND_START_TIME_TO': 'F.GOOGLE.EXPORT_TIME.ROUND_START_TIME_TO',
        'ROUND_TIME_WORKED_TO': 'F.GOOGLE.EXPORT_TIME.ROUND_TIME_WORKED_TO',
        'SAVE_ROW': 'F.GOOGLE.EXPORT_TIME.SAVE_ROW',
        'SNACK_EQUAL_VALUES': 'F.GOOGLE.EXPORT_TIME.SNACK_EQUAL_VALUES',
        'SNACK_ROW_APPENDED': 'F.GOOGLE.EXPORT_TIME.SNACK_ROW_APPENDED'
      },
      'SNACKS': {
        'DOWNLOADING_UPDATE': 'F.GOOGLE.SNACKS.DOWNLOADING_UPDATE',
        'ERROR': 'F.GOOGLE.SNACKS.ERROR',
        'ERROR_INITIAL_IMPORT': 'F.GOOGLE.SNACKS.ERROR_INITIAL_IMPORT',
        'LOCAL_UP_TO_DATE': 'F.GOOGLE.SNACKS.LOCAL_UP_TO_DATE',
        'MULTIPLE_SYNC_FILES_WITH_SAME_NAME': 'F.GOOGLE.SNACKS.MULTIPLE_SYNC_FILES_WITH_SAME_NAME',
        'NO_UPDATE_REQUIRED': 'F.GOOGLE.SNACKS.NO_UPDATE_REQUIRED',
        'REMOTE_UP_TO_DATE': 'F.GOOGLE.SNACKS.REMOTE_UP_TO_DATE',
        'SUCCESS': 'F.GOOGLE.SNACKS.SUCCESS',
        'SYNCING': 'F.GOOGLE.SNACKS.SYNCING'
      }
    }
  },
  'FILE_IMEX': {
    'EXPORT_DATA': 'FILE_IMEX.EXPORT_DATA',
    'IMPORT_FROM_FILE': 'FILE_IMEX.IMPORT_FROM_FILE'
  },
  'F_AUTO_BACKUPS': {
    'HELP': 'F_AUTO_BACKUPS.HELP',
    'LABEL_IS_ENABLED': 'F_AUTO_BACKUPS.LABEL_IS_ENABLED',
    'TITLE': 'F_AUTO_BACKUPS.TITLE'
  },
  'F_GOOGLE_DRIVE_SYNC': {
    'HELP': 'F_GOOGLE_DRIVE_SYNC.HELP',
    'TITLE': 'F_GOOGLE_DRIVE_SYNC.TITLE'
  },
  'F_IDLE': {
    'HELP': 'F_IDLE.HELP',
    'IS_ENABLE_IDLE_TIME_TRACKING': 'F_IDLE.IS_ENABLE_IDLE_TIME_TRACKING',
    'IS_ONLY_OPEN_IDLE_WHEN_CURRENT_TASK': 'F_IDLE.IS_ONLY_OPEN_IDLE_WHEN_CURRENT_TASK',
    'IS_UN_TRACKED_IDLE_RESETS_BREAK_TIMER': 'F_IDLE.IS_UN_TRACKED_IDLE_RESETS_BREAK_TIMER',
    'MIN_IDLE_TIME': 'F_IDLE.MIN_IDLE_TIME',
    'TITLE': 'F_IDLE.TITLE'
  },
  'F_IMEX': {
    'HELP': 'F_IMEX.HELP',
    'TITLE': 'F_IMEX.TITLE'
  },
  'F_KEYBOARD': {
    'ADD_NEW_NOTE': 'F_KEYBOARD.ADD_NEW_NOTE',
    'ADD_NEW_TASK': 'F_KEYBOARD.ADD_NEW_TASK',
    'APP_WIDE_SHORTCUTS': 'F_KEYBOARD.APP_WIDE_SHORTCUTS',
    'COLLAPSE_SUB_TASKS': 'F_KEYBOARD.COLLAPSE_SUB_TASKS',
    'EXPAND_SUB_TASKS': 'F_KEYBOARD.EXPAND_SUB_TASKS',
    'FOCUS_LAST_ACTIVE_TASK': 'F_KEYBOARD.FOCUS_LAST_ACTIVE_TASK',
    'GLOBAL_SHOW_HIDE': 'F_KEYBOARD.GLOBAL_SHOW_HIDE',
    'GLOBAL_TOGGLE_TASK_START': 'F_KEYBOARD.GLOBAL_TOGGLE_TASK_START',
    'GO_TO_DAILY_AGENDA': 'F_KEYBOARD.GO_TO_DAILY_AGENDA',
    'GO_TO_FOCUS_MODE': 'F_KEYBOARD.GO_TO_FOCUS_MODE',
    'GO_TO_SETTINGS': 'F_KEYBOARD.GO_TO_SETTINGS',
    'GO_TO_WORK_VIEW': 'F_KEYBOARD.GO_TO_WORK_VIEW',
    'HELP': 'F_KEYBOARD.HELP',
    'MOVE_TASK_DOWN': 'F_KEYBOARD.MOVE_TASK_DOWN',
    'MOVE_TASK_UP': 'F_KEYBOARD.MOVE_TASK_UP',
    'MOVE_TO_BACKLOG': 'F_KEYBOARD.MOVE_TO_BACKLOG',
    'MOVE_TO_TODAYS_TASKS': 'F_KEYBOARD.MOVE_TO_TODAYS_TASKS',
    'OPEN_PROJECT_NOTES': 'F_KEYBOARD.OPEN_PROJECT_NOTES',
    'SELECT_NEXT_TASK': 'F_KEYBOARD.SELECT_NEXT_TASK',
    'SELECT_PREVIOUS_TASK': 'F_KEYBOARD.SELECT_PREVIOUS_TASK',
    'SYSTEM_SHORTCUTS': 'F_KEYBOARD.SYSTEM_SHORTCUTS',
    'TASK_ADD_SUB_TASK': 'F_KEYBOARD.TASK_ADD_SUB_TASK',
    'TASK_DELETE': 'F_KEYBOARD.TASK_DELETE',
    'TASK_EDIT_TITLE': 'F_KEYBOARD.TASK_EDIT_TITLE',
    'TASK_OPEN_ESTIMATION_DIALOG': 'F_KEYBOARD.TASK_OPEN_ESTIMATION_DIALOG',
    'TASK_SCHEDULE': 'F_KEYBOARD.TASK_SCHEDULE',
    'TASK_SHORTCUTS': 'F_KEYBOARD.TASK_SHORTCUTS',
    'TASK_SHORTCUTS_INFO': 'F_KEYBOARD.TASK_SHORTCUTS_INFO',
    'TASK_TOGGLE_ADDITIONAL_INFO_OPEN': 'F_KEYBOARD.TASK_TOGGLE_ADDITIONAL_INFO_OPEN',
    'TASK_TOGGLE_DONE': 'F_KEYBOARD.TASK_TOGGLE_DONE',
    'TITLE': 'F_KEYBOARD.TITLE',
    'TOGGLE_BACKLOG': 'F_KEYBOARD.TOGGLE_BACKLOG',
    'TOGGLE_BOOKMARKS': 'F_KEYBOARD.TOGGLE_BOOKMARKS',
    'TOGGLE_PLAY': 'F_KEYBOARD.TOGGLE_PLAY',
    'ZOOM_DEFAULT': 'F_KEYBOARD.ZOOM_DEFAULT',
    'ZOOM_IN': 'F_KEYBOARD.ZOOM_IN',
    'ZOOM_OUT': 'F_KEYBOARD.ZOOM_OUT'
  },
  'F_LANG': {
    'AR': 'F_LANG.AR',
    'DE': 'F_LANG.DE',
    'EN': 'F_LANG.EN',
    'ES': 'F_LANG.ES',
    'FR': 'F_LANG.FR',
    'JA': 'F_LANG.JA',
    'LABEL': 'F_LANG.LABEL',
    'RU': 'F_LANG.RU',
    'TITLE': 'F_LANG.TITLE',
    'TR': 'F_LANG.TR',
    'ZH': 'F_LANG.ZH'
  },
  'F_MISC': {
    'HELP': 'F_MISC.HELP',
    'IS_AUTO_MARK_PARENT_AS_DONE': 'F_MISC.IS_AUTO_MARK_PARENT_AS_DONE',
    'IS_CONFIRM_BEFORE_EXIT': 'F_MISC.IS_CONFIRM_BEFORE_EXIT',
    'IS_DISABLE_REMIND_WHEN_FORGOT_TO_FINISH_DAY': 'F_MISC.IS_DISABLE_REMIND_WHEN_FORGOT_TO_FINISH_DAY',
    'IS_HIDE_NAV': 'F_MISC.IS_HIDE_NAV',
    'IS_NOTIFY_WHEN_TIME_ESTIMATE_EXCEEDED': 'F_MISC.IS_NOTIFY_WHEN_TIME_ESTIMATE_EXCEEDED',
    'TITLE': 'F_MISC.TITLE',
    'isDisableRemindWhenForgotToFinishDay': 'F_MISC.isDisableRemindWhenForgotToFinishDay',
    'isHideNav': 'F_MISC.isHideNav',
    'isNotifyWhenTimeEstimateExceeded': 'F_MISC.isNotifyWhenTimeEstimateExceeded'
  },
  'F_POMODORO': {
    'BREAK_DURATION': 'F_POMODORO.BREAK_DURATION',
    'CYCLES_BEFORE_LONGER_BREAK': 'F_POMODORO.CYCLES_BEFORE_LONGER_BREAK',
    'DURATION': 'F_POMODORO.DURATION',
    'HELP': 'F_POMODORO.HELP',
    'IS_ENABLED': 'F_POMODORO.IS_ENABLED',
    'IS_MANUAL_CONTINUE': 'F_POMODORO.IS_MANUAL_CONTINUE',
    'IS_PLAY_SOUND': 'F_POMODORO.IS_PLAY_SOUND',
    'IS_PLAY_SOUND_AFTER_BREAK': 'F_POMODORO.IS_PLAY_SOUND_AFTER_BREAK',
    'IS_PLAY_TICK': 'F_POMODORO.IS_PLAY_TICK',
    'IS_STOP_TRACKING_ON_BREAK': 'F_POMODORO.IS_STOP_TRACKING_ON_BREAK',
    'LONGER_BREAK_DURATION': 'F_POMODORO.LONGER_BREAK_DURATION',
    'TITLE': 'F_POMODORO.TITLE'
  },
  'F_TAKE_A_BREAK': {
    'HELP': 'F_TAKE_A_BREAK.HELP',
    'IS_ENABLED': 'F_TAKE_A_BREAK.IS_ENABLED',
    'MESSAGE': 'F_TAKE_A_BREAK.MESSAGE',
    'MIN_WORKING_TIME': 'F_TAKE_A_BREAK.MIN_WORKING_TIME',
    'TITLE': 'F_TAKE_A_BREAK.TITLE'
  },
  'G': {
    'CANCEL': 'G.CANCEL',
    'DISMISS': 'G.DISMISS',
    'SAVE': 'G.SAVE',
    'TITLE': 'G.TITLE'
  },
  'MH': {
    'ADD_NEW_TASK': 'MH.ADD_NEW_TASK',
    'CREATE_PROJECT': 'MH.CREATE_PROJECT',
    'GO_TO_TASK_LIST': 'MH.GO_TO_TASK_LIST',
    'MANAGE_PROJECTS': 'MH.MANAGE_PROJECTS',
    'METRICS': 'MH.METRICS',
    'PROCRASTINATE': 'MH.PROCRASTINATE',
    'PROJECTS': 'MH.PROJECTS',
    'PROJECT_MENU': 'MH.PROJECT_MENU',
    'SETTINGS': 'MH.SETTINGS',
    'TASKS': 'MH.TASKS',
    'TASK_LIST': 'MH.TASK_LIST',
    'TOGGLE_SHOW_BOOKMARKS': 'MH.TOGGLE_SHOW_BOOKMARKS',
    'TOGGLE_SHOW_NOTES': 'MH.TOGGLE_SHOW_NOTES',
    'TOGGLE_TRACK_TIME': 'MH.TOGGLE_TRACK_TIME',
    'WORKLOG': 'MH.WORKLOG'
  },
  'PDS': {
    'BACK': 'PDS.BACK',
    'BREAK_LABEL': 'PDS.BREAK_LABEL',
    'CELEBRATE': 'PDS.CELEBRATE',
    'CLEAR_ALL_CONTINUE': 'PDS.CLEAR_ALL_CONTINUE',
    'EVALUATION': 'PDS.EVALUATION',
    'EXPORT_TASK_LIST': 'PDS.EXPORT_TASK_LIST',
    'GOOGLE_SHEET': 'PDS.GOOGLE_SHEET',
    'NO_TASKS': 'PDS.NO_TASKS',
    'ROUND_15M': 'PDS.ROUND_15M',
    'ROUND_30M': 'PDS.ROUND_30M',
    'ROUND_5M': 'PDS.ROUND_5M',
    'ROUND_TIME_SPENT': 'PDS.ROUND_TIME_SPENT',
    'ROUND_TIME_SPENT_TITLE': 'PDS.ROUND_TIME_SPENT_TITLE',
    'ROUND_TIME_WARNING': 'PDS.ROUND_TIME_WARNING',
    'ROUND_UP_15M': 'PDS.ROUND_UP_15M',
    'ROUND_UP_30M': 'PDS.ROUND_UP_30M',
    'ROUND_UP_5M': 'PDS.ROUND_UP_5M',
    'SAVE_AND_GO_HOME': 'PDS.SAVE_AND_GO_HOME',
    'START_END': 'PDS.START_END',
    'SUMMARY_FOR': 'PDS.SUMMARY_FOR',
    'TASKS_COMPLETED': 'PDS.TASKS_COMPLETED',
    'TASK_LIST': 'PDS.TASK_LIST',
    'TIME_SPENT_AND_ESTIMATE_LABEL': 'PDS.TIME_SPENT_AND_ESTIMATE_LABEL',
    'TIME_SPENT_ESTIMATE_TITLE': 'PDS.TIME_SPENT_ESTIMATE_TITLE',
    'TODAY': 'PDS.TODAY',
    'WEEK': 'PDS.WEEK'
  },
  'PM': {
    'TITLE': 'PM.TITLE'
  },
  'PP': {
    'ARCHIVED_PROJECTS': 'PP.ARCHIVED_PROJECTS',
    'ARCHIVE_PROJECT': 'PP.ARCHIVE_PROJECT',
    'CREATE_NEW': 'PP.CREATE_NEW',
    'DELETE_PROJECT': 'PP.DELETE_PROJECT',
    'EDIT_PROJECT': 'PP.EDIT_PROJECT',
    'EXPORT_PROJECT': 'PP.EXPORT_PROJECT',
    'GITHUB_CONFIGURED': 'PP.GITHUB_CONFIGURED',
    'IMPORT_FROM_FILE': 'PP.IMPORT_FROM_FILE',
    'JIRA_CONFIGURED': 'PP.JIRA_CONFIGURED',
    'TITLE': 'PP.TITLE',
    'UN_ARCHIVE_PROJECT': 'PP.UN_ARCHIVE_PROJECT'
  },
  'PS': {
    'GLOBAL_SETTINGS': 'PS.GLOBAL_SETTINGS',
    'PROJECT_SETTINGS': 'PS.PROJECT_SETTINGS'
  },
  'S': {
    'SYNC': {
      'ERROR_FALLBACK_TO_BACKUP': 'S.SYNC.ERROR_FALLBACK_TO_BACKUP',
      'ERROR_INVALID_DATA': 'S.SYNC.ERROR_INVALID_DATA',
      'IMPORTING': 'S.SYNC.IMPORTING',
      'SUCCESS': 'S.SYNC.SUCCESS'
    }
  },
  'WW': {
    'ADD_MORE': 'WW.ADD_MORE',
    'ADD_SOME_TASKS': 'WW.ADD_SOME_TASKS',
    'COMPLETED_TASKS': 'WW.COMPLETED_TASKS',
    'ESTIMATE_REMAINING': 'WW.ESTIMATE_REMAINING',
    'FINISH_DAY': 'WW.FINISH_DAY',
    'HELP_PROCRASTINATION': 'WW.HELP_PROCRASTINATION',
    'NO_COMPLETED_TASKS': 'WW.NO_COMPLETED_TASKS',
    'NO_PLANNED_TASKS': 'WW.NO_PLANNED_TASKS',
    'READY_TO_WORK': 'WW.READY_TO_WORK',
    'TIME_ESTIMATED': 'WW.TIME_ESTIMATED',
    'WITHOUT_BREAK': 'WW.WITHOUT_BREAK',
    'WORKING_TODAY': 'WW.WORKING_TODAY'
  }
};
