export const T = {
  'G': {
    'SAVE': 'G.SAVE',
    'DISMISS': 'G.DISMISS'
  },
  'F_LANG': {
    'LABEL': 'F_LANG.LABEL',
    'EN': 'F_LANG.EN',
    'DE': 'F_LANG.DE',
    'TR': 'F_LANG.TR',
    'FR': 'F_LANG.FR',
    'AR': 'F_LANG.AR',
    'ZH': 'F_LANG.ZH',
    'RU': 'F_LANG.RU',
    'JA': 'F_LANG.JA'
  },
  'F_MISC': {
    'HELP': 'F_MISC.HELP',
    'IS_AUTO_MARK_PARENT_AS_DONE': 'F_MISC.IS_AUTO_MARK_PARENT_AS_DONE',
    'IS_CONFIRM_BEFORE_EXIT': 'F_MISC.IS_CONFIRM_BEFORE_EXIT',
    'isDisableRemindWhenForgotToFinishDay': 'F_MISC.isDisableRemindWhenForgotToFinishDay',
    'IS_HIDE_NAV': 'F_MISC.IS_HIDE_NAV',
    'IS_NOTIFY_WHEN_TIME_ESTIMATE_EXCEEDED': 'F_MISC.IS_NOTIFY_WHEN_TIME_ESTIMATE_EXCEEDED'
  },
  'WW': {
    'ADD_MORE': 'WW.ADD_MORE',
    'ADD_SOME_TASKS': 'WW.ADD_SOME_TASKS',
    'ESTIMATE_REMAINING': 'WW.ESTIMATE_REMAINING',
    'FINISH_DAY': 'WW.FINISH_DAY',
    'HELP_PROCRASTINATION': 'WW.HELP_PROCRASTINATION',
    'NO_PLANNED_TASKS': 'WW.NO_PLANNED_TASKS',
    'COMPLETED_TASKS': 'WW.COMPLETED_TASKS',
    'NO_COMPLETED_TASKS': 'WW.NO_COMPLETED_TASKS',
    'READY_TO_WORK': 'WW.READY_TO_WORK',
    'TIME_ESTIMATED': 'WW.TIME_ESTIMATED',
    'WITHOUT_BREAK': 'WW.WITHOUT_BREAK',
    'WORKING_TODAY': 'WW.WORKING_TODAY'
  },
  'PS': {
    'PROJECT_SETTINGS': 'PS.PROJECT_SETTINGS',
    'GLOBAL_SETTINGS': 'PS.GLOBAL_SETTINGS'
  },
  'PDS': {
    'BACK': 'PDS.BACK',
    'CELEBRATE': 'PDS.CELEBRATE',
    'SUMMARY_FOR': 'PDS.SUMMARY_FOR',
    'START_END': 'PDS.START_END',
    'TASKS_COMPLETED': 'PDS.TASKS_COMPLETED',
    'TIME_SPENT_AND_ESTIMATE_LABEL': 'PDS.TIME_SPENT_AND_ESTIMATE_LABEL',
    'TIME_SPENT_ESTIMATE_TITLE': 'PDS.TIME_SPENT_ESTIMATE_TITLE',
    'BREAK_LABEL': 'PDS.BREAK_LABEL',
    'EVALUATION': 'PDS.EVALUATION',
    'WEEK': 'PDS.WEEK',
    'GOOGLE_SHEET': 'PDS.GOOGLE_SHEET',
    'TODAY': 'PDS.TODAY',
    'TASK_LIST': 'PDS.TASK_LIST',
    'NO_TASKS': 'PDS.NO_TASKS',
    'ROUND_TIME_SPENT': 'PDS.ROUND_TIME_SPENT',
    'ROUND_TIME_SPENT_TITLE': 'PDS.ROUND_TIME_SPENT_TITLE',
    'EXPORT_TASK_LIST': 'PDS.EXPORT_TASK_LIST',
    'ROUND_TIME_WARNING': 'PDS.ROUND_TIME_WARNING',
    'ROUND_5M': 'PDS.ROUND_5M',
    'ROUND_UP_5M': 'PDS.ROUND_UP_5M',
    'ROUND_15M': 'PDS.ROUND_15M',
    'ROUND_UP_15M': 'PDS.ROUND_UP_15M',
    'ROUND_30M': 'PDS.ROUND_30M',
    'ROUND_UP_30M': 'PDS.ROUND_UP_30M',
    'SAVE_AND_GO_HOME': 'PDS.SAVE_AND_GO_HOME',
    'CLEAR_ALL_CONTINUE': 'PDS.CLEAR_ALL_CONTINUE'
  },
  'PM': {
    'TITLE': 'PM.TITLE'
  },
  'PP': {
    'TITLE': 'PP.TITLE',
    'JIRA_CONFIGURED': 'PP.JIRA_CONFIGURED',
    'GITHUB_CONFIGURED': 'PP.GITHUB_CONFIGURED',
    'EDIT_PROJECT': 'PP.EDIT_PROJECT',
    'ARCHIVE_PROJECT': 'PP.ARCHIVE_PROJECT',
    'UN_ARCHIVE_PROJECT': 'PP.UN_ARCHIVE_PROJECT',
    'EXPORT_PROJECT': 'PP.EXPORT_PROJECT',
    'DELETE_PROJECT': 'PP.DELETE_PROJECT',
    'CREATE_NEW': 'PP.CREATE_NEW',
    'IMPORT_FROM_FILE': 'PP.IMPORT_FROM_FILE',
    'ARCHIVED_PROJECTS': 'PP.ARCHIVED_PROJECTS'
  },
  'AAA': 'AAA'
};
