const PREFIX = 'ngStorage-';
export const STORAGE_PROJECTS = PREFIX + 'projects';
export const STORAGE_CURRENT_PROJECT = PREFIX + 'currentProject';
export const STORAGE_TASKS = PREFIX + 'tasks';
export const STORAGE_CONFIG = PREFIX + 'config';
export const STORAGE_BACKLOG_TASKS = PREFIX + 'backlogTasks';
export const STORAGE_DONE_BACKLOG_TASKS = PREFIX + 'doneBacklogTasks';
export const STORAGE_JIRA_SETTINGS = PREFIX + 'jiraSettings';
export const STORAGE_THEME = PREFIX + 'theme';
