export const IPC_EVENT_SHUTDOWN = 'SHUTDOWN';
export const IPC_EVENT_SHUTDOWN_NOW = 'SHUTDOWN_NOW';
export const IPC_JIRA_CB_EVENT = 'JIRA_RESPONSE';
export const IPC_JIRA_MAKE_REQUEST_EVENT = 'JIRA';
export const IPC_REGISTER_GLOBAL_SHORTCUT_EVENT = 'REGISTER_GLOBAL_SHORTCUT';
export const IPC_EVENT_IDLE_TIME = 'IDLE_TIME';

export const IPC_EVENT_APP_READY = 'APP_READY';
export const IPC_EVENT_ERROR = 'ELECTRON_ERROR';
export const IPC_EVENT_CURRENT_TASK_UPDATED = 'CHANGED_CURRENT_TASK';
export const IPC_EVENT_TASK_MARK_AS_DONE = 'TASK_MARK_AS_DONE';
export const IPC_EVENT_TASK_START = 'TASK_START';
export const IPC_EVENT_TASK_PAUSE = 'TASK_PAUSE';

export const IPC_EVENT_TRIGGER_GOOGLE_AUTH = 'TRIGGER_GOOGLE_AUTH';
export const IPC_EVENT_GOOGLE_AUTH_TOKEN = 'GOOGLE_AUTH_TOKEN';
export const IPC_EVENT_GOOGLE_AUTH_TOKEN_ERROR = 'GOOGLE_AUTH_TOKEN_ERROR';

export const IPC_TRANSFER_SETTINGS_REQUESTED = 'TRANSFER_SETTINGS_REQUESTED';
export const IPC_TRANSFER_SETTINGS_TO_ELECTRON = 'TRANSFER_SETTINGS_TO_ELECTRON';

export const maybe_UPDATE_CURRENT_TASK = 'UPDATE_CURRENT_TASK';
export const maybe_IS_IDLE = 'IS_IDLE';
export const maybe_IS_BUSY = 'IS_BUSY';
export const maybe_IPC_EVENT_POMODORO_UPDATE = 'IPC_EVENT_POMODORO_UPDATE';
export const maybe_PROJECT_CHANGED = 'PROJECT_CHANGED';
export const maybe_COMPLETE_DATA_RELOAD = 'COMPLETE_DATA_RELOAD';
