export const IPC_EVENT_SHUTDOWN = 'SHUTDOWN';
export const IPC_EVENT_SHUTDOWN_NOW = 'SHUTDOWN_NOW';
export const IPC_JIRA_CB_EVENT = 'JIRA_RESPONSE';
export const IPC_JIRA_MAKE_REQUEST_EVENT = 'JIRA';
export const IPC_REGISTER_GLOBAL_SHORTCUT_EVENT = 'REGISTER_GLOBAL_SHORTCUT';
